### PR TITLE
test 

### PR DESCRIPTION
**Pull request by abhithakre**

### CODE REVIEW

**Comment by rowi1de** [comment]
@abhithakre you will have to run `npm run build`

**Comment by abhithakre** [comment]
Sure,
 I am new in CI/CD ,can you help me for adding this feature(auto assign review) in my repo , so as per my understanding just i need to add 
action.yml,
 index.js and
 workflow( main.yml) file.

any other required file ?
Thanks in advance.

**Comment by rowi1de** [comment]
> Sure,
> I am new in CI/CD ,can you help me for adding this feature(auto assign review) in my repo , so as per my understanding just i need to add
> action.yml,
> index.js and
> workflow( main.yml) file.
> 
> any other required file ?
> Thanks in advance.

> Sure,
> I am new in CI/CD ,can you help me for adding this feature(auto assign review) in my repo , so as per my understanding just i need to add
> action.yml,
> index.js and
> workflow( main.yml) file.
> 
> any other required file ?
> Thanks in advance.

Hey you don't need much:
Just go to your repo, click the "actions" tab, "new workflow" and it will guide you

**Comment by rowi1de** [comment]
https://github.com/rowi1de/auto-assign-review-teams#example-usage please see the readme how to use this

**Comment by abhithakre** [comment]
thanks @rowi1de  👍

**Pull request closed without merging**
